default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  database: <%= ENV['DATABASE_NAME_DEV'] %>
  <<: *default

test:
  database: <%= ENV['DATABASE_NAME_TEST'] %>
  <<: *default

production:
  <<: *default
